services:
  pmforge:
    build: .
    volumes:
      - ..:/pmforge
      - ${HOME}/.gitconfig:/home/vscode/.gitconfig:ro
    tty: true
    network_mode: host  # linux host only
    ports:
      - "19132:19132/udp"
